volumes:
  pgprod:
services:
  migrator-prod:
    build:
      dockerfile: ./migration_prod.Dockerfile
    depends_on:
      pg-prod:
        condition: service_healthy
    env_file:
      - ./prod.env

  pg-prod:
    image: postgres
    env_file:
      - ./prod.env
    ports:
      - "54324:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgprod:/var/lib/postgresql/data